# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [2]:
np.__version__

'1.16.5'

### Display array elements in reverse order

In [6]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.flip(a)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### Triple elements in array

In [8]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

### Create array with 20 zeros; every fifth element equals four

In [9]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

### Transpose the rows and columns

In [10]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Create a 5x5 identity matrix with integer components

In [26]:
np.asmatrix(np.eye(5,dtype=int))

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [18]:
b=np.random.randn(10)
b.mean()
# b.size

-0.19762778328722902

#### Repeat, and visually estimate the mean for the sum of the two means

#### Repeat, and visually estimate the mean for the sum of the two means

### Create an 8x8 checker board with alternating zeros and ones

In [25]:
np.tile([0,1],32).reshape(8,8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### Create a sorted vector that contain 'n' random numbers

### Without sorting, replace largest element in random array with the value 1234

### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [27]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [29]:
struct=np.array(camelot_values,dtype=camelot_dtype)

In [37]:
struct=np.sort(struct,order="height",)

In [38]:
struct

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

### Make an array read-only (immutable)

In [48]:
a.flags.writeable=False
a[0]=1

ValueError: assignment destination is read-only

### Print enumerated values from a 3x3 NumPy array