# Views and Copies

In [2]:
import numpy as np

In [3]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [4]:
su_casa = mi_casa

### Same or Different?

In [7]:
#reference equality
mi_casa is su_casa

True

In [8]:
id(mi_casa)

4481339184

In [9]:
id(su_casa)

4481339184

In [10]:
#value inequality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [11]:
su_casa[4] = 1010

In [12]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [13]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [14]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [15]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [16]:
tree_house == mi_casa

array([ True,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [17]:
id(tree_house)

4400009088

In [18]:
id(mi_casa)

4481339184

In [19]:
tree_house[0] = 214

In [20]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [21]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [22]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [23]:
tree_house is mi_casa

False

## View: a shallow copy

In [25]:
farm_house = tree_house.view()
farm_house.shape = (2,4)

In [26]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [27]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [28]:
tree_house [3] = -111

In [29]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

## Deep Copy


In [30]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [31]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])